/* eslint-disable quotes */
import pc from 'picocolors';

interface HelpSection {
  id: string;
  title: string;
  icon: string;
  content: string[];
}

export const HELP_SECTIONS: HelpSection[] = [
  {
    id: 'welcome',
    title: 'Welcome',
    icon: '👋',
    content: [
      pc.bold('Welcome to flutterkill!'),
      '',
      'Flutterkill helps you find and manage build artifacts',
      'and caches left behind by Flutter/Dart development.',
      '',
      'These folders are essential while working on projects,',
      'but over time they pile up, eating tons of space long',
      "after you've moved on.",
      '',
      'Flutterkill scans your directories, lists these folders with',
      'their sizes, and shows when you last touched each project,',
      'so you can quickly decide what to keep and what to clean.',
      '',
      pc.green(pc.bold('Easy and powerful!')),
    ],
  },
  {
    id: 'shortcuts',
    title: 'Quick Reference',
    icon: '⌨️',
    content: [
      pc.cyan(pc.bold('Navigation')),
      `  ${pc.green('↑/↓ or j/k')}       Move cursor.`,
      `  ${pc.green('←/→ or h/l')}       Switch panels.`,
      `  ${pc.green('PgUp/PgDown')}      Fast scroll.`,
      `  ${pc.green('Home/End')}         Jump to first/last.`,
      '',
      pc.cyan(pc.bold('Actions (normal mode)')),
      `  ${pc.green('SPACE / DEL')}      Delete folder.`,
      `  ${pc.green('o')}                Open parent folder.`,
      `  ${pc.green('/')}                Search (Regex supported).`,
      `  ${pc.green('t')}                Enter ${pc.green('multi-select mode')}.`,
      '',
      pc.cyan(pc.bold('Actions (multi-select mode)')),
      `  ${pc.green('t')}                Back to ${pc.green('normal mode')} without delete.`,
      `  ${pc.green('v')}                Range selection.`,
      `  ${pc.green('a')}                Select/deselect all.`,
      `  ${pc.green('SPACE')}            Select/deselect current.`,
      `  ${pc.green('ENTER')}            Delete selected folders.`,
      '',
      pc.cyan(pc.bold('Others')),
      `  ${pc.green('e')}                Show errors.`,
      `  ${pc.green('q / ESC')}          Quit flutterkill.`,
    ],
  },
  {
    id: 'header',
    title: 'Header Info',
    icon: '📊',
    content: [
      pc.bold('Understanding the header'),
      '',
      pc.bold(pc.green('Potential Space')),
      'The total size of all detected directories.',
      'This represents the maximum possible space you could',
      'free if you deleted everything.',
      '',
      pc.bold(pc.green('Freed Space')),
      'The space actually recovered in this session.',
      '',
      pc.bold(pc.green('Last Modified (age)')),
      'Shows when the last file in the parent workspace was',
      'modified. This helps identify abandoned projects.',
      '',
      pc.dim('Note: This checks the entire parent directory,'),
      pc.dim('not just the target folder itself.'),
      '',
      pc.bold(pc.green('Progress Bar')),
      'The progress bar has 3 color-coded parts:',
      '',
      ` ${pc.green('▀▀▀▀')} Green  → Results ready (stats calculated)`,
      ` ${pc.white('▀▀▀▀')} White  → Directories examined`,
      ` ${pc.gray('▀▀▀▀')} Gray   → Pending to be analyzed`,
      '',
      'Full bar example:',
      ` ${pc.green('▀▀▀▀▀▀▀')}${pc.white('▀▀▀▀')}${pc.gray('▀▀▀▀▀▀▀▀▀▀▀')}`,
    ],
  },
  {
    id: 'warnings',
    title: 'Warnings',
    icon: '⚠️',
    content: [
      pc.bold(pc.yellow('Important: Not all results are safe to delete!')),
      '',
      'Some applications (VSCode, Discord, Slack, etc.) need',
      'their dependencies to work. If their directory is deleted,',
      'the application will probably break until dependencies',
      'are reinstalled.',
      '',
      'Flutterkill will try to detect this folders and show "⚠️"',
      'alongside the result and mark it as "sensitive".',
      '',
      '',
      pc.bold(pc.green('Pro tip')),
      'Use the Info panel (→) to see more information',
      'about why a folder is flagged.',
    ],
  },
  {
    id: 'panels',
    title: 'Panels',
    icon: '📋',
    content: [
      pc.bold('Understanding the interface'),
      '',
      pc.bold(pc.cyan('Delete Panel (Main)')),
      'Lists all found directories with their sizes.',
      'Navigate with arrow keys or j/k.',
      'Press SPACE to delete a folder.',
      'Press → to see details.',
      '',
      pc.bold(pc.cyan('Info Panel')),
      'Shows details of the selected result. Plus notes',
      'that might be useful to you.',
      '',
      pc.bold(pc.cyan('Options Panel')),
      'Configure flutterkill settings on the fly.',
      '',
      pc.bold(pc.cyan('Help Panel (You are here!)')),
      'Navigate through help sections.',
      'Use ↑/↓ to change sections.',
      'Scroll content with j/k or arrow keys.',
    ],
  },
  //   { // TODO pending to add .npkillrc support
  //     id: 'config',
  //     title: 'Configuration',
  //     icon: '⚙️',
  //     content: [
  //       colors.bold('Customizing npkill with .npkillrc'),
  //       '',
  //       colors.bold.cyan('What is .npkillrc?'),
  //       'A configuration file where you can set your default',
  //       'preferences, custom profiles, and target folders.',
  //       '',
  //       colors.bold.cyan('Location'),
  //       '',
  //       'Place it in your home directory:',
  //       colors.dim('  ~/.npkillrc'),
  //       '',
  //       'Or load from a custom location:',
  //       colors.green('  npkill --config /path/to/config'),
  //       '',
  //       colors.bold.cyan('Example Configuration'),
  //       '',
  //       colors.dim('{'),
  //       colors.dim('  "targets": ["node_modules", ".venv", "target"],'),
  //       colors.dim('  "exclude": [".git", "important-project"],'),
  //       colors.dim('  "sortBy": "size",'),
  //       colors.dim('  "excludeSensitiveResults": true,'),
  //       colors.dim('  "profiles": {'),
  //       colors.dim('    "mystack": {'),
  //       colors.dim('      "targets": ["node_modules", "venv", "target"]'),
  //       colors.dim('    }'),
  //       colors.dim('  }'),
  //       colors.dim('}'),
  //       '',
  //       colors.bold.cyan('Available Options'),
  //       `${colors.green('targets')}              Target folder names to search`,
  //       `${colors.green('exclude')}              Directories to skip`,
  //       `${colors.green('sortBy')}               Default sort (size/path/age)`,
  //       `${colors.green('sizeUnit')}             Display unit (auto/mb/gb)`,
  //       `${colors.green('profiles')}             Custom profile definitions`,
  //     ],
  //   },
  {
    id: 'profiles',
    title: 'Profiles',
    icon: '📦',
    content: [
      pc.bold('Working with profiles'),
      '',
      pc.bold(pc.cyan('What are profiles?')),
      'Profiles are presets of target folders for different',
      'programming languages and tools.',
      '',
      pc.bold(pc.cyan('Usage')),
      'List available profiles:',
      pc.green('  flutterkill -p'),
      '',
      'Single profile:',
      pc.green('  flutterkill -p flutter'),
      '',
      'Multiple profiles:',
      pc.green('  flutterkill -p flutter,python,java'),
      '',
      // colors.bold.cyan('Custom Profiles'),
      //   'Define your own in .npkillrc:',
      //   '',
      //   colors.dim('"profiles": {'),
      //   colors.dim('  "webdev": {'),
      //   colors.dim('    "targets": ["node_modules", "dist", ".next"]'),
      //   colors.dim('  }'),
      //   colors.dim('}'),
      //   '',
      //   'Then use:',
      // colors.green('  npkill -p webdev'),
    ],
  },
  {
    id: 'tips',
    title: 'Tips & Tricks',
    icon: '💡',
    content: [
      pc.bold('Get the most out of flutterkill'),
      '',
      pc.bold(pc.cyan('1. Use profiles')),
      '   Start with profiles for common tools:',
      `   ${pc.green('flutterkill -p flutter,python,java')}.`,
      '',
      pc.bold(pc.cyan('2. Sort intelligently')),
      '   Sort by size to find the biggest space hogs:',
      `   ${pc.green('flutterkill --sort size')}`,
      '   Or by age to find abandoned projects.',
      '',
      pc.bold(pc.cyan('3. Exclude what you need')),
      '   Protect important directories:',
      `   ${pc.green('flutterkill -E ".git,important_project"')}`,
      '',
      pc.bold(pc.cyan('4. Try dry-run mode')),
      '   Test without risk using --dry-run.',
      '   Nothing is deleted! (simulated with delay).',
      '',
      pc.bold(pc.cyan('5. Multi-select workflow')),
      '   Press "t" to enter selection mode.',
      '   Mark folders with SPACE.',
      '   Press ENTER to delete all at once.',
      '',
      '   Press "v" on first item.',
      '   Move to last item and press "v" again.',
      '   All items in between are selected!',
      '',
      pc.bold(pc.cyan('6. Check details first')),
      '   Unsure about a result? Press → to see',
      '   more details.',
    ],
  },
  {
    id: 'about',
    title: 'About',
    icon: 'ℹ️',
    content: [
      pc.bold('About flutterkill'),
      '',
      'Flutterkill, a tool designed to help Flutter developers',
      'reclaim disk space by finding and removing',
      'unnecessary build artifacts and caches.',
      '',
      pc.bold(pc.cyan('Get Involved')),
      'Based on npkill (github.com/voidcosmos/npkill)',
      'Report bugs, request features, contribute!',
      '',
      pc.bold(pc.cyan('License')),
      'MIT License - Free and open source.',
      '',
      '',
      pc.dim('Made with ❤️'),
    ],
  },
];
